# Generated by Django 2.2.2 on 2019-07-31 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('nameproduct', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=70)),
                ('category', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.Clientes')),
                ('productos', models.ManyToManyField(to='Ecommerce.Productos')),
            ],
        ),
    ]
