# Generated by Django 2.2.2 on 2019-08-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='photo',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
