# Generated by Django 2.2.2 on 2019-08-03 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0002_auto_20190801_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalItem', models.IntegerField()),
                ('finalPrice', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='productos',
        ),
        migrations.AddField(
            model_name='invoice',
            name='productos',
            field=models.ManyToManyField(through='Ecommerce.InvoiceItems', to='Ecommerce.Productos'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.Invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='productos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.Productos'),
        ),
    ]
