# Generated by Django 2.2.2 on 2019-09-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0005_auto_20190919_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
